version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  CSS_MODE: ${CSS_MODE-optimized}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.virgon.base.parameter1.com/graphql}
  EQUIPMENT_EXPERTS_GRAPHQL_URI: ${EQUIPMENT_EXPERTS_GRAPHQL_URI-https://equipment-experts.virgon.base.parameter1.com/graphql}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  CONTENT_METER_VIEW_LIMIT: ${CONTENT_METER_VIEW_LIMIT-3}
  IDX_NAV_ENABLE: ${IDX_NAV_ENABLE-false}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}
  INBODY_PUSHDOWN_INJECTION: ${INBODY_PUSHDOWN_INJECTION-false}

x-env-virgon-dev: &env-virgon-dev
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10103}
  OEMBED_URI: ${OEMBED_URI-https://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10203}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10303}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.virgon.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.virgon.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.virgon.base.parameter1.com}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  eqw:
    <<: *site-cmd
    working_dir: /root/sites/equipmentworld.com
    environment:
      <<: *env
      HOST: www-rr-eqw.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9901
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19901
      OMEDA_INPUT_ID: ${EQW_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-eqw.dev.parameter1.com
    ports:
      - "9901:80"
      - "19901:19901"

  tlc:
    <<: *site-cmd
    working_dir: /root/sites/totallandscapecare.com
    environment:
      <<: *env
      HOST: www-rr-tlc.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9902
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19902
      OMEDA_INPUT_ID: ${TLC_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-tlc.dev.parameter1.com
    ports:
      - "9902:80"
      - "19902:19902"

  tn:
    <<: *site-cmd
    working_dir: /root/sites/truckersnews.com
    environment:
      <<: *env
      HOST: www-rr-tn.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9903
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19903
      OMEDA_INPUT_ID: ${TN_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-tn.dev.parameter1.com
    ports:
      - "9903:80"
      - "19903:19903"

  ccj:
    <<: *site-cmd
    working_dir: /root/sites/ccjdigital.com
    environment:
      <<: *env
      HOST: www-rr-ccj.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9904
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19904
      OMEDA_INPUT_ID: ${CCJ_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-ccj.dev.parameter1.com
    ports:
      - "9904:80"
      - "19904:19904"

  ct:
    <<: *site-cmd
    working_dir: /root/sites/cleantrucking.com
    environment:
      <<: *env
      HOST: www-rr-ct.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9913
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19913
      OMEDA_INPUT_ID: ${CT_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-ct.dev.parameter1.com
    ports:
      - "9913:80"
      - "19913:19913"

  hwt:
    <<: *site-cmd
    working_dir: /root/sites/hardworkingtrucks.com
    environment:
      <<: *env
      HOST: www-rr-hwt.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9905
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19905
      OMEDA_INPUT_ID: ${HWT_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-hwt.dev.parameter1.com
    ports:
      - "9905:80"
      - "19905:19905"

  thr:
    <<: *site-cmd
    working_dir: /root/sites/truckhistoryreport.com
    environment:
      <<: *env
      HOST: www-rr-thr.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9909
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19909
      OMEDA_INPUT_ID: ${THR_OMEDA_INPUT_ID-(unset)}
      RIGDIG_USERNAME: ${RIGDIG_USERNAME}
      RIGDIG_PASSWORD: ${RIGDIG_PASSWORD}
      PAYFABRIC_DEVICE_ID: ${PAYFABRIC_DEVICE_ID}
      PAYFABRIC_DEVICE_PWD: ${PAYFABRIC_DEVICE_PWD}
      PAYFABRIC_GATEWAY_NAME: ${PAYFABRIC_GATEWAY_NAME-EVO US_CC}
      PAYFABRIC_ENV: ${PAYFABRIC_ENV-SANDBOX}
      PAYFABRIC_PAYMENT_METHODS: ${PAYFABRIC_PAYMENT_METHODS-CreditCard}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
      DEBUG: rigdig,payfabric,sendgrid
    hostname: www-rr-thr.dev.parameter1.com
    ports:
      - "9909:80"
      - "19909:19909"

  ovd:
    <<: *site-cmd
    working_dir: /root/sites/overdriveonline.com
    environment:
      <<: *env
      HOST: www-rr-ovd.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9906
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19906
      OMEDA_INPUT_ID: ${OVD_OMEDA_INPUT_ID-(unset)}
      RIGDIG_USERNAME: ${RIGDIG_USERNAME}
      RIGDIG_PASSWORD: ${RIGDIG_PASSWORD}
      PAYFABRIC_DEVICE_ID: ${PAYFABRIC_DEVICE_ID}
      PAYFABRIC_DEVICE_PWD: ${PAYFABRIC_DEVICE_PWD}
      PAYFABRIC_GATEWAY_NAME: ${PAYFABRIC_GATEWAY_NAME-EVO US_CC}
      PAYFABRIC_ENV: ${PAYFABRIC_ENV-SANDBOX}
      PAYFABRIC_PAYMENT_METHODS: ${PAYFABRIC_PAYMENT_METHODS-CreditCard}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
      DEBUG: rigdig,payfabric,sendgrid
      ENABLE_RIGDIG: ${ENABLE_RIGDIG-true}
    hostname: www-rr-ovd.dev.parameter1.com
    ports:
      - "9906:80"
      - "19906:19906"

  tps:
    <<: *site-cmd
    working_dir: /root/sites/truckpartsandservice.com
    environment:
      <<: *env
      HOST: www-rr-tps.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9907
      GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
      LIVERELOAD_PORT: 19907
      OMEDA_INPUT_ID: ${TPS_OMEDA_INPUT_ID-(unset)}
    hostname: www-rr-tps.dev.parameter1.com
    ports:
      - "9907:80"
      - "19907:19907"
